#!/bin/bash
echo Compiling ...
nasm -f elf64 -o $1.o $1.asm
ld -o $1 $1.o

echo Compiled !!!

echo ==========================================================
echo ==========================================================
echo Running the program :
echo

./$1